Add AssertLockHeld to suppress clang error
clang showed the following error:
wallet/wallet.cpp:2577:17: error: calling function 'IsLockedCoin'
  requires holding mutex 'cs_wallet' exclusively
  [-Werror,-Wthread-safety-analysis]
            if (IsLockedCoin(entry.first, i)) {
                ^

Signed-off-by: Azat Nizametdinov <azat@thirdhash.com>